spring:
  web:
    encoding:
      charset: UTF-8  # 웹 응답 인코딩 설정
  http:
    encoding:
      charset: UTF-8  # HTTP 응답 인코딩 설정
      enabled: true
      force: true  # 인코딩을 강제로 적용
  datasource:
    url: jdbc:mysql://localhost:3307/${MYSQL_DATABASE}?useSSL=false&serverTimezone=Asia/Seoul&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true&useLegacyDatetimeCode=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect  # MySQL8Dialect로 설정
        jdbc:
          time_zone: UTC
        format_sql: true